Desktop version
danielochuba/Portfolio-setup-and-mobile-first pull request #4
Opened 2023-01-20 21:23 UTC by danielochuba

Build the Desktop version of the Portfolio, Using a responsive media Queries

2023-01-20 22:20 UTC, RaoAkif requested changes
## STATUS: REQUIRED CHANGES ♻️

Hi @danielochuba, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Required Changes ♻️
_Check the comments under the review._
<img src="https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966" />

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 22:20 UTC, RaoAkif commented on index.html
> +
Your design is looking great, but the purpose of this project is to make a design as close to FIGMA design as possible.

| Your Design  | FIGMA Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/61361037/213812164-d5eae42c-d037-4b49-9d25-0bada941023c.png)  | ![image](https://user-images.githubusercontent.com/61361037/213812245-5a243371-ef19-4b69-abe9-e110247b6f18.png)  |

2023-01-20 22:20 UTC, RaoAkif commented on index.html
> +                                        <span class="see-project see-project-vis "><a href="">See project</a></span>
It seems that this button has misaligned while adding some query. Try to make a design as close to FIGMA design as possible.

| Your Design  | FIGMA Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/61361037/213812896-928b2fc6-f088-47af-9e82-ff247b1cdf56.png)  | ![image](https://user-images.githubusercontent.com/61361037/213812956-707972f3-2e79-4031-82bb-433a9a9be714.png)  |

2023-01-20 22:20 UTC, RaoAkif commented on index.html
> +                            <h2 class="about-me">About me</h2>
It seems that this button has been misaligned while adding some query. I have tested your design between `760 - 1440` sizes, it's looking the same.

Try to make a design as close to FIGMA design as possible.

| Your Design  | FIGMA Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/61361037/213813391-59dc8347-33ca-4575-8ed5-60045d5919a6.png)  | ![image](https://user-images.githubusercontent.com/61361037/213813422-c4fcf81a-00df-4a94-89b5-34ef50b8be7e.png)  |

2023-01-20 22:20 UTC, RaoAkif commented on index.html
> +
#### In the next section from the highlighted one:

The bullet points are different from the ones mentioned in the FIGMA design. Also look at the `Skill` word. It is pushed forward
Try to make a design as close to FIGMA design as possible.

| Your Design  | FIGMA Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/61361037/213814311-419fabf0-fc91-4a02-ac0e-725cc42064c3.png) | ![image](https://user-images.githubusercontent.com/61361037/213814141-6f509108-01c0-49f3-b785-cc1ff119098c.png)  |

2023-01-20 22:20 UTC, RaoAkif commented on desktop.css
> +
Try to make a design as close to FIGMA design as possible.

 Your Design:
 ![image](https://user-images.githubusercontent.com/61361037/213814931-35349048-b09f-4a53-903c-bfaaa751b318.png)
FIGMA Design:
![image](https://user-images.githubusercontent.com/61361037/213815157-ff69d8a0-cf9e-4f3f-9c3a-699bdd15ebd3.png)

2023-01-21 13:36 UTC, GedeonTS approved these changes
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @danielochuba ,

Your are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"> 

## Highlights :clap: :tophat: 
- No linter errors :+1: 
- Good use of Github flow :+1: 
## Optional suggestions :small_airplane: 
- [OPTIONAL]  Kindly make sure you have the future feature in your README as recommended by Microverse.
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 13:36 UTC, GedeonTS commented on index.html
> +                        <h1 class="title">My Recent Works </h1>
- [OPTIONAL] Kindly make sure your work section is centered as per the Figma design:
- [OPTIONAL] Kindly make sure there is a hover effect to these cards as show in the design:

![Screenshot from 2023-01-21 14-38-39](https://user-images.githubusercontent.com/97834160/213868171-85818219-bb03-4e4f-accc-764afb528d7d.png)

2023-01-21 13:36 UTC, GedeonTS commented on index.html
>                              </label>
- [OPTIONAL] I think would be better to make sure the text area is aligned with the other inputs as in the Figma design

__After checking out the commit before the previous review I noticed that the errors were there before, that's why it's optional for now.__

- Your design:
![Screenshot from 2023-01-21 15-31-30](https://user-images.githubusercontent.com/97834160/213869126-55bcb681-8bf8-4a80-a3f8-d9ba27d6bf3c.png)


- Figma:

![Screenshot from 2023-01-21 14-40-27](https://user-images.githubusercontent.com/97834160/213869082-d8db67ca-7ddb-4065-9b4c-c8b8d9d53e94.png)

2023-01-21 14:13 UTC, merged